### ISSUE TITLE
Add caching or remove nix from pipeline build steps

### ISSUE THREAD

**Issue by ramizpolic** [bank-vaults/vault-operator#105]
Configuring the NIX environment takes 3 minutes for every pipeline step, making it one of the longest pipeline steps. Using Makefile should be comparably faster + configuring other setup steps (e.g. configuring Go) can be fully cached between runs. If it is possible to add cache to nix, then it is worth considering as well.

**Comment by sagikazarmark** [comment]
Here is a potential solution: https://discourse.nixos.org/t/the-magic-nix-cache-a-github-action-for-speeding-up-your-nix-workflows/29665

**Comment by sagikazarmark** [comment]
BTW I'm less concerned about 3 minutes than reproducibility and portable environments.
