### ISSUE TITLE
Support different imagePullPolicy options 

### ISSUE THREAD

**Issue by SvenMark** [bank-vaults/vault-operator#149]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.

### Problem Description

The operator doesn't support other image pull policies in the pods the operator creates. We need this functionality because of a security requirement that requires us to set the image pull policy of all pods to Always. The default implemented in the operator is IfNotPresent.

### Proposed Solution

Add a configuration option to support different image pull policies for the pods that are created by the operator.

**Comment by akijakya** [comment]
Hi @SvenMark, thanks for using Bank-Vaults! You can change the default image pull policy in the chart: https://github.com/bank-vaults/vault-operator/blob/81fdb6c04e422c30acebab5a6321ae6ce514901b/deploy/charts/vault-operator/values.yaml#L13

**Comment by SvenMark** [comment]
Thanks for the reply. The feature I'm looking for is not changing the image pull policy of the operator itself. Rather it's changing the pull policy for the pods that are created by the operator through the vault.banzaicloud.com/v1alpha1 Vault CRD.

For example:
https://github.com/bank-vaults/vault-operator/blob/81fdb6c04e422c30acebab5a6321ae6ce514901b/pkg/controller/vault/vault_controller.go#L921

**Comment by akijakya** [comment]
Looking at the CRD it is theoretically also possible by defining all the necessary containers in `spec.vaultPodSpec.containers` but a new configuration value would definitely be a much better solution, thanks for the suggestion!

**Comment by sagikazarmark** [comment]
Setting PodSpec should be enough of a solution for now. We will see if we can add an additional option.
