### ISSUE TITLE
`Unable to retrieve credentials` error when installing vault-operator

### ISSUE THREAD

**Issue by Kenblair1226** [bank-vaults/vault-operator#162]
Was trying to install vault-operator but getting the following error. Seems there is a permission issue.
```
Error: GET "https://ghcr.io/v2/bank-vaults/helm-charts/vault-operator/tags/list": unable to retrieve credentials
```

➜ helm version
version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.6"}

**Comment by sagikazarmark** [comment]
Can't seem to be able to reproduce. Do you have any credentials specified for ghcr.io?

**Comment by Kenblair1226** [comment]
I have github credentials set in my home directory. Does ghcr.io need special credentials?

**Comment by Kenblair1226** [comment]
I figured it out! It's my first time using ghcr.io, didn't know it need explicitly login with github token. It works now! Thanks.
