### ISSUE TITLE
Gather details for feature requests

### ISSUE THREAD

**Issue by ramizpolic** [bank-vaults/vault-operator#239]
https://github.com/bank-vaults/vault-operator/issues/149
https://github.com/bank-vaults/vault-operator/issues/231
and any other requested

**Comment by sando38** [comment]
Hello there,

The HashiCorp's helm-chart in HA mode provides a service, which only points to the "active" vault pod:
https://github.com/hashicorp/vault-helm/blob/main/templates/server-ha-active-service.yaml

This is useful for example for the UI, as the service from the operator's vault CR currently directs to inactive pods as well, which cannot be used for UI purposes.

If it is supported differently, then I am happy for any hint from your side ;)

Thanks in advance and wish you a great day
saarko

**Comment by sando38** [comment]
Second question/ feature request:

When using templates with the vault-agent as in the example in your [documentation](https://bank-vaults.dev/docs/mutating-webhook/vault-agent-templating/#use-vault-ttls):

```hcl
    template {
      contents = <<EOH
        {{- with secret "database/creds/readonly" }}
        username: {{ .Data.username }}
        password: {{ .Data.password }}
        {{ end }}
      EOH
      destination = "/etc/secrets/config"
      command     = "/bin/sh -c \"kill -HUP $(pidof vault-demo-app) || true\""
    }
```
I get the following error:
```
2023-10-24T01:14:00.384Z [ERROR] agent.template.server: template server error: error="error rendering \"(dynamic)\" => \"/etc/secrets/settings.json\": failed writing file: mkdir /etc/secrets: permission denied"
```

If I use the path `/vault/secrets` it works out of the box. From the generated manifests I can see, that a volume like this is generated

```yaml
    volumeMounts:
      - name: agent-secrets
        mountPath: /vault/secrets
  volumes:
    - name: agent-secrets
      emptyDir:
        medium: Memory
```

Would it be possible to make the path for the volumeMount `agent-secrets` configurable with an environment variable/ annotation?

**Comment by akijakya** [comment]
Hi, @sando38, thanks for using Bank-Vaults! Please add these as separate issues to the project so we can track them independently. Meanwhile, we are taking a look at the problem!

**Comment by sando38** [comment]
> Hi, @sando38, thanks for using Bank-Vaults! Please add these as separate issues to the project so we can track them independently. Meanwhile, we are taking a look at the problem!

Thanks! Will do so. And thanks for offering bank vaults!
