### ISSUE TITLE
Fix CI Action in case of main merge

### ISSUE THREAD

**Issue by akijakya** [bank-vaults/vault-operator#25]
It seems to me that every time there is a merge to the main branch, the `CI` Github Action fails, more precisely the acceptance tests with an error I seen locally when I forgot to load the vault-operator image into the kind cluster and the operator pod has an `ErrImageNeverPull` error  (I didn't verify this by logging into a Github runner though)... 
Although the CI runs slightly different on merge to main than on an open PR, I couldn't find during my first look what causes things to go sideways.

**Comment by sagikazarmark** [comment]
Fixed
