### ISSUE TITLE
[vault-configurer] Vault pod's added capabilities cannot be removed 

### ISSUE THREAD

**Issue by ahmed-kadri** [bank-vaults/vault-operator#314]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
Vault pod is not created because it violates PodSecurityPolicy, added capabilities are forbidden.
I'm not able to disable these added capabilities.
I tried setting this but it doesn't work.

    apiVersion: "vault.banzaicloud.com/v1alpha1"  
    kind: "Vault"  
    metadata:  
      name: "vault"  
    spec:  
      vaultContainerSpec:  
        name: vault  
        securityContext:  
          runAsNonRoot: true  
          runAsUser: 1000  
          runAsGroup: 1000  
          privileged: false  
          readOnlyRootFilesystem: true  
          allowPrivilegeEscalation: false  
          capabilities:  
            drop:  
              - IPC_LOCK

**Expected behaviour**:
I want to disable the added capabilities in Vault pod.

**Steps to reproduce the bug**:
I installed the operator (v1.17.0) and then applied a manifest to create a Vault CRD.

**Additional context**:
I can't disable the PodSecurityPolicy. I have to remove these added capabilities somehow.

**Environment details**:
Kubernetes version (e.g. v1.10.2): v1.24.8
Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): GCP
bank-vaults version (e.g. 0.4.17): latest
Install method (e.g. helm or static manifests): Operator (Helm)
Logs from the misbehaving component (and any other relevant logs)

    Events:                                                                                                                                                    │
    │   Type     Reason        Age                    From                    Message                                                                            │
    │   ----     ------        ----                   ----                    -------                                                                            │
    │   Warning  FailedCreate  4m10s (x32 over 4h2m)  statefulset-controller  create Pod vault-0 in StatefulSet vault failed error: pods "vault-0" is forbidden: │
    │  violates PodSecurity "baseline:latest": non-default capabilities (container "vault" must not include "IPC_LOCK" in securityContext.capabilities.add) 

 

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
Manifest used: https://github.com/banzaicloud/bank-vaults/blob/main/operator/deploy/cr.yaml

/kind bug

**Comment by ramizpolic** [comment]
@ahmed-kadri-tt could you please let us know if this is still the same behaviour?
