### ISSUE TITLE
Vault-Operator Chart enable ability to change log level

### ISSUE THREAD

**Issue by cten** [bank-vaults/vault-operator#329]
**Feature request**
By default the Operator's log level is set to "debug". 

**Describe the solution you'd like**
Add the ability in the chart templates to set the log level through values

**Comment by akijakya** [comment]
Hi @cten, sorry for the long delay. This issue is not likely to become high priority in the foreseeable future for us, but sounds like an easy fix, if you are still interested in the solution, contributions are always welcome! 🙂
