### ISSUE TITLE
allow to configure vault and bank-vaults image pull secrets

### ISSUE THREAD

**Issue by longkai** [bank-vaults/vault-operator#330]
**Is your feature request related to a problem? Please describe.**
Currently we can only set the vault-operator image pull secret. The other components like vault and bank-vaults are populate from controller in client-go.

In our environment, we have to pull a dedicated vault image from private registry.

**Describe the solution you'd like**
Allow config optional image pull secret from vault and bank-vaults.

**Describe alternatives you've considered**
No.

**Additional context**
I have modified the controller code to satisfy our needs. If you think the proposal is rational I'd like to make a contribution!

**Comment by akijakya** [comment]
Hi @longkai, sorry for the long delay. This issue is not likely to become high priority in the foreseeable future for us, but sounds like an easy fix, if you are still interested in the solution, contributions are always welcome! 🙂
