### ISSUE TITLE
Why doesn't vault trust itself?

### ISSUE THREAD

**Issue by larsks** [bank-vaults/vault-operator#379]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

1.21.2

### Installation Type

Official Helm chart

### Kubernetes Version

1.26.6

### Kubernetes Distribution/Provisioner

OpenShift

### Expected Behavior

I expect to be able to `kubectl exec` into a vault pod and run vault commands, but instead running vault commands (like `vault status`) fails with an unknown certificate error.

A simple solution is to to run:

```
export VAULT_CACERT=/vault/tls/ca.crt
```

After this, `vault` commands run inside a vault pod behave as expected. We should add the `VAULT_CACERT` variable to the pod configuration.

### Actual Behavior

```
$ kubectl exec -it vault-0 -- sh
/vault # vault status
Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Steps To Reproduce

(see above)

**Comment by akijakya** [comment]
Hi, @larsks, thanks for your observation! I guess most people interact with the Vault instance in the way described [here](https://bank-vaults.dev/docs/operator/#deploy-operator) under section 4. But contributions are always welcome! 😊
