### ISSUE TITLE
Helm chart is missing capabilities config

### ISSUE THREAD

**Issue by olga-salesloft** [bank-vaults/vault-operator#387]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

v1.21.2

### Installation Type

Official Helm chart

### Bank-Vaults Version

v1.31.0

### Kubernetes Version

1.27.0

### Kubernetes Distribution/Provisioner

GKE

### Expected Behavior

PDB template has been added recently https://github.com/bank-vaults/vault-operator/pull/324/files and it should works. 

### Actual Behavior

However, I see the error with PDB template
```
template: vault-operator/templates/pdb.yaml:2:15: executing "vault-operator/templates/pdb.yaml" at <include "common.capabilities.policy.apiVersion" .>: error calling include: template: no template "common.capabilities.policy.apiVersion" associated with template "gotpl"
```

I believe this `common.capabilities.policy.apiVersion` should be define in `_helpers.tpl` or separate file `_capabilities.tpl` or in `chart.yaml` as dependence but it doesn't.
Kindly ask if someone can have a look?

**Comment by adrianmoisey** [comment]
Ping.

**Comment by csatib02** [comment]
Hi @olga-salesloft,

Thanks for submitting this issue, this is definitely something that should be added, but I don't know whether we are going to have the time for this in the future, but all contributions are welcome.

**Comment by csatib02** [comment]
Fixed by: https://github.com/bank-vaults/vault-operator/pull/527
