### ISSUE TITLE
Vault Service Account should be managed by the Operator

### ISSUE THREAD

**Issue by longnbao** [bank-vaults/vault-operator#429]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

The Vault's service account is a part of Vault and should be managed by the Operator

### Proposed Solution

- Vault operators should have the capability to create, modify, and delete service accounts within the Vault environment. This includes defining account names, associated policies, and any necessary configurations.
- Operators should be able to assign or modify policies for each service account, controlling the access and permissions granted to different parts.
- Customization the annotations or labels to connect to cloud workload identity

**Comment by Elyytscha** [comment]
vote for this, it feels really inconvenient to deploy those resources additional:

![image](https://github.com/bank-vaults/vault-operator/assets/10408311/24b2d33e-9f6a-42c5-850b-21e5b0142d95)
