### ISSUE TITLE
Init container config-templating failing due to permission issue while restoring the backup from velero

### ISSUE THREAD

**Issue by smarimus** [bank-vaults/vault-operator#431]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

1.21.2

### Installation Type

Official Helm chart

### Kubernetes Version

1.25.9

### Kubernetes Distribution/Provisioner

RKE2

### Expected Behavior

I'm backing up the vault resource and restoring using velero and restic.

The backup operation is successful
The restore operation is giving the below exception.

`λ k logs vault-0 config-templating

time="2024-04-12T19:09:02Z" **level=fatal msg="error writing template file \"/vault/config/vault.json\": open /vault/config/vault.json: permission denied**"`

### Actual Behavior

Should be able to restore the backup from velero.
Looks like there's no option to provide security context.
https://github.com/bank-vaults/vault-operator/blob/d95312400fee4a29ec6234ab23e9a90ff5906c1c/pkg/controller/vault/vault_controller.go#L1295

### Logs

```shell
λ k logs vault-0 config-templating

time="2024-04-12T19:09:02Z" level=fatal msg="error writing template file \"/vault/config/vault.json\": open /vault/config/vault.json: permission denied"
```

**Comment by rosieks** [comment]
I have the same issue
