### ISSUE TITLE
Banazai operator : CA secrets distributed by operator in all namespace causing errors in Cert Manager Ca Injector 

### ISSUE THREAD

**Issue by kumarBiplab1987** [bank-vaults/vault-operator#478]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/vault-operator/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Operator Version

v1.22.1

### Installation Type

Helm

### Bank-Vaults Version

 v1.31.0

### Kubernetes Version

v1.25.5

### Kubernetes Distribution/Provisioner

rancher

### Expected Behavior

When distributing CA certs through operator it should not copy the cert manager annotations in the vault tls secrets.

### Actual Behavior

We are using cert manager to manage the certificates of all vault services in our kubernetes cluster.
When we are trying to create a namespace for our services, Banzai is automatically creating secret includes ca cert in that namespace, which is having cert manager annotations in the metadata of the secret resource and cert manager CA injector pod is complains that associated certificates resource with the secret is not present in that namespace.

cert-manager/secret-for-certificate-mapper "msg"="unable to fetch certificate that owns the secret" "error"="Certificate.cert-manager.io "vault" not found" "certificate"={"Namespace":"infra","Name":"vault"} "secret"={"Namespace":"infra","Name":"vault-tls"}

### Steps To Reproduce

1. Install Banzai vault operator.
2. Use Cert manager to generate vault certificates.
3. Use "existingTlsSecretName: vault-tls" in the crd when bringing up the vault services.

### Logs

```shell
Logs from the cert manager CA injector
cert-manager/secret-for-certificate-mapper "msg"="unable to fetch certificate that owns the secret" "error"="Certificate.cert-manager.io "vault" not found" "certificate"={"Namespace":"infra","Name":"vault"} "secret"={"Namespace":"infra","Name":"vault-tls"}
```

**Comment by kumarBiplab1987** [comment]
Linking the existing defect https://github.com/bank-vaults/vault-operator/issues/124

**Comment by csatib02** [comment]
Closing in favour of the original issue: https://github.com/bank-vaults/vault-operator/issues/124
